terraform {
  required_providers {
    infisical = {
      # version = <latest version>
      source = "infisical/infisical"
    }
  }
}

provider "infisical" {
  host = "https://app.infisical.com" # Only required if using self hosted instance of Infisical, default is https://app.infisical.com
  auth = {
    universal = {
      client_id     = "<machine-identity-client-id>"
      client_secret = "<machine-identity-client-secret>"
    }
  }
}

resource "infisical_project" "example" {
  name = "example"
  slug = "example"
}

# Enforce naming and strength requirements on static secrets in production.
resource "infisical_secret_validation_rule" "prod_static_secrets" {
  project_id       = infisical_project.example.id
  name             = "production-secret-standards"
  description      = "Naming and strength requirements for production secrets"
  environment_slug = "prod"
  secret_path      = "/**"

  rule = {
    type = "static-secrets"
    constraints = [
      {
        type       = "required-prefix"
        applies_to = "key"
        value      = "PROD_"
      },
      {
        type       = "min-length"
        applies_to = "value"
        value      = "16"
      },
      {
        type       = "prevent-value-reuse"
        applies_to = "value"
        value      = "5"
      },
    ]
  }
}

# Constrain the passwords generated by dynamic secret leases. Omitting environment_slug
# applies the rule to every environment in the project.
resource "infisical_secret_validation_rule" "dynamic_secret_passwords" {
  project_id  = infisical_project.example.id
  name        = "dynamic-secret-password-policy"
  secret_path = "/**"

  rule = {
    type      = "dynamic-secrets"
    providers = ["sql-database"]
    constraints = [
      {
        type       = "min-length"
        applies_to = "password"
        value      = "24"
      },
    ]
  }
}

# Stage a secret rotation password policy without enforcing it yet.
resource "infisical_secret_validation_rule" "rotation_passwords" {
  project_id  = infisical_project.example.id
  name        = "rotation-password-policy"
  secret_path = "/services/**"
  is_active   = false

  rule = {
    type      = "secret-rotations"
    providers = ["postgres-credentials"]
    constraints = [
      {
        type       = "regex-pattern"
        applies_to = "password"
        value      = "^[A-Za-z0-9]{32}$"
      },
    ]
  }
}
